# [ws_002]

In [0]:
USE [master]
GO

In [0]:
/****** Object:  Database [ws_002]    Script Date: 15.12.2023 11:27:21 ******/
CREATE DATABASE [ws_002]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ws_002', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\ws_002.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'ws_002_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\ws_002_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [ws_002] SET COMPATIBILITY_LEVEL = 140
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ws_002].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [ws_002] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [ws_002] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [ws_002] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [ws_002] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [ws_002] SET ARITHABORT OFF 
GO
ALTER DATABASE [ws_002] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [ws_002] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [ws_002] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [ws_002] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [ws_002] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [ws_002] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [ws_002] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [ws_002] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [ws_002] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [ws_002] SET  ENABLE_BROKER 
GO
ALTER DATABASE [ws_002] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [ws_002] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [ws_002] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [ws_002] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [ws_002] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [ws_002] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [ws_002] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [ws_002] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [ws_002] SET  MULTI_USER 
GO
ALTER DATABASE [ws_002] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [ws_002] SET DB_CHAINING OFF 
GO
ALTER DATABASE [ws_002] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [ws_002] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [ws_002] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [ws_002] SET QUERY_STORE = OFF
GO

# [dbo].[Country]

In [0]:
USE [ws_002]
GO

In [0]:
/****** Object:  Table [dbo].[Country]    Script Date: 15.12.2023 11:27:21 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Country](
	[Code] [char](2) NOT NULL,
	[Name] [nvarchar](255) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Code] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[Hotel]

In [0]:
/****** Object:  Table [dbo].[Hotel]    Script Date: 15.12.2023 11:27:21 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Hotel](
	[id] [int] NOT NULL,
	[Name] [nvarchar](255) NOT NULL,
	[CountOfStars] [int] NOT NULL,
	[CountryCode] [char](2) NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[HotelComment]

In [0]:
/****** Object:  Table [dbo].[HotelComment]    Script Date: 15.12.2023 11:27:21 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HotelComment](
	[id] [int] NOT NULL,
	[Hotelid] [int] NOT NULL,
	[Text] [nvarchar](max) NOT NULL,
	[Author] [nvarchar](255) NOT NULL,
	[CreationDate] [date] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

# [dbo].[HotelImage]

In [0]:
/****** Object:  Table [dbo].[HotelImage]    Script Date: 15.12.2023 11:27:21 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HotelImage](
	[id] [int] NOT NULL,
	[Hotelid] [int] NOT NULL,
	[ImageSource] [nvarchar](max) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

# [dbo].[HotelOfTour]

In [0]:
/****** Object:  Table [dbo].[HotelOfTour]    Script Date: 15.12.2023 11:27:21 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HotelOfTour](
	[HotelId] [int] NOT NULL,
	[TourId] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[HotelId] ASC,
	[TourId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[Tour]

In [0]:
/****** Object:  Table [dbo].[Tour]    Script Date: 15.12.2023 11:27:21 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Tour](
	[id] [int] NOT NULL,
	[TicketCount] [int] NOT NULL,
	[Name] [nvarchar](255) NOT NULL,
	[Description] [nvarchar](max) NULL,
	[ImagePreview] [nvarchar](max) NULL,
	[Price] [decimal](10, 2) NOT NULL,
	[isActual] [bit] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

# [dbo].[Type]

In [0]:
/****** Object:  Table [dbo].[Type]    Script Date: 15.12.2023 11:27:21 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Type](
	[id] [int] NOT NULL,
	[Name] [nvarchar](255) NOT NULL,
	[Description] [nvarchar](max) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

# [dbo].[TypeOfTour]

In [0]:
/****** Object:  Table [dbo].[TypeOfTour]    Script Date: 15.12.2023 11:27:21 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TypeOfTour](
	[TypeId] [int] NOT NULL,
	[TourId] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[TypeId] ASC,
	[TourId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

# [FK__Hotel__CountryCo__1AD3FDA4]

In [0]:
ALTER TABLE [dbo].[Hotel]  WITH CHECK ADD FOREIGN KEY([CountryCode])
REFERENCES [dbo].[Country] ([Code])
GO

# [FK__HotelComm__Hotel__22751F6C]

In [0]:
ALTER TABLE [dbo].[HotelComment]  WITH CHECK ADD FOREIGN KEY([Hotelid])
REFERENCES [dbo].[Hotel] ([id])
GO

# [FK__HotelImag__Hotel__1F98B2C1]

In [0]:
ALTER TABLE [dbo].[HotelImage]  WITH CHECK ADD FOREIGN KEY([Hotelid])
REFERENCES [dbo].[Hotel] ([id])
GO

# [FK__HotelOfTo__Hotel__2B0A656D]

In [0]:
ALTER TABLE [dbo].[HotelOfTour]  WITH CHECK ADD FOREIGN KEY([HotelId])
REFERENCES [dbo].[Hotel] ([id])
GO

# [FK__HotelOfTo__TourI__2BFE89A6]

In [0]:
ALTER TABLE [dbo].[HotelOfTour]  WITH CHECK ADD FOREIGN KEY([TourId])
REFERENCES [dbo].[Tour] ([id])
GO

# [FK__TypeOfTou__TourI__282DF8C2]

In [0]:
ALTER TABLE [dbo].[TypeOfTour]  WITH CHECK ADD FOREIGN KEY([TourId])
REFERENCES [dbo].[Tour] ([id])
GO

# [FK__TypeOfTou__TypeI__2739D489]

In [0]:
ALTER TABLE [dbo].[TypeOfTour]  WITH CHECK ADD FOREIGN KEY([TypeId])
REFERENCES [dbo].[Type] ([id])
GO

# [ws_002]

In [0]:
USE [master]
GO

In [0]:
ALTER DATABASE [ws_002] SET  READ_WRITE 
GO